"""T2: Triton built-in warp specialization for the single-dot TMA gate/up vs the current kernel
(single GPU, sm_90, synthetic data).

Kernels: tma-cur (ref_gu._epg_gu_kernel, od15 config), ws-k (ws_gu K-loop WS, 4 warps) and its
WS-off control, ws-p (ws_gu persistent, WS on the tile loop, grid = SM count) and its WS-off
control. Each candidate's BF16 output is compared word by word with tma-cur ("mism" column).
Time = triton.testing.do_bench median (ms). FLOP = 2 * M * H * 2I.
usage: python bench.py [--M 2048,8192,16384] [--H 4096] [--I 2048,8192] [--E 8] [--warps 4,8]
                      [--json ../results/T2_ws.json] [--md ../results/T2_ws.md]
Output: a markdown table (paste it into results.md).
"""
import argparse
import json
import os
import time

import torch
import triton

import ref_gu
import ws_gu


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--M", default="2048,8192,16384")
    ap.add_argument("--H", type=int, default=4096)
    ap.add_argument("--I", default="2048,8192")
    ap.add_argument("--E", type=int, default=8)
    ap.add_argument("--warps", default="4,8")
    ap.add_argument("--json", default="")
    ap.add_argument("--md", default="")
    a = ap.parse_args()
    rows = []
    if not ref_gu.is_hopper():
        print("SKIP bench: needs sm_90")
        return
    p = torch.cuda.get_device_properties(0)
    print(f"GPU {p.name}, {p.multi_processor_count} SMs, H={a.H}, E={a.E}")
    print("| M | I | kernel | warps | ms | vs tma-cur | mism |")
    print("|---|---|---|---|---|---|---|")
    for I in [int(v) for v in a.I.split(",")]:
        for M in [int(v) for v in a.M.split(",")]:
            P = ref_gu.make_problem(M, a.H, I, a.E, seed=7, gather=False)
            d = ref_gu.tma_descs(P)
            act0, am0 = ref_gu.out_buffers(P)

            def run(f):
                f()
                torch.cuda.synchronize()
                return triton.testing.do_bench(f, warmup=25, rep=100)
            t0 = run(lambda: ref_gu.run_ref_tma(P, act0, am0, d))
            print(f"| {M} | {I} | tma-cur | 8 | {t0:.4f} | - | 0 |", flush=True)
            rows.append(dict(kernel="tma-cur", warps=8, shape=f"M={M} H={a.H} I={I} E={a.E}",
                             time_us=round(t0 * 1000, 2), ref_time_us=round(t0 * 1000, 2),
                             gain_pct=0.0, bytes_equal=True, mismatch_words=0))
            ref = act0.view(torch.int16).clone()
            for w in [int(v) for v in a.warps.split(",")]:
                for name, f in (("ws-k", lambda o, m: ws_gu.run_ws(P, o, m, d, True, w)),
                                ("ws-k off", lambda o, m: ws_gu.run_ws(P, o, m, d, False, w)),
                                ("ws-p", lambda o, m: ws_gu.run_ws_persistent(P, o, m, d, True, False, w)),
                                ("ws-p off", lambda o, m: ws_gu.run_ws_persistent(P, o, m, d, False, False, w))):
                    act, am = ref_gu.out_buffers(P)
                    try:
                        t = run(lambda: f(act, am))
                        mism = int((act.view(torch.int16) != ref).sum())
                        rows.append(dict(kernel=name, warps=w, shape=f"M={M} H={a.H} I={I} E={a.E}",
                                         time_us=round(t * 1000, 2), ref_time_us=round(t0 * 1000, 2),
                                         gain_pct=round(100 * (t0 / t - 1), 1),
                                         bytes_equal=(mism == 0), mismatch_words=mism))
                        print(f"| {M} | {I} | {name} | {w} | {t:.4f} | {100 * (t0 / t - 1):+.1f}% | {mism} |",
                              flush=True)
                    except Exception as e:
                        print(f"| {M} | {I} | {name} | {w} | err: {repr(e).splitlines()[0][:80]} | | |",
                              flush=True)
                        rows.append(dict(kernel=name, warps=w, shape=f"M={M} H={a.H} I={I} E={a.E}",
                                         error=repr(e).splitlines()[0][:300]))
    if a.json:
        os.makedirs(os.path.dirname(os.path.abspath(a.json)), exist_ok=True)
        json.dump(dict(gpu=f"{p.name} ({p.multi_processor_count} SMs)", triton=triton.__version__,
                       triton_path=os.path.dirname(triton.__file__),
                       updated=time.strftime("%Y-%m-%d %H:%M:%S %z"), rows=rows),
                  open(a.json, "w"), indent=1)
        print("json:", a.json)
    if a.md:
        with open(a.md, "w") as f:
            f.write(f"# T2 warp specialization (auto-generated by bench.py)\n\nGPU {p.name}, "
                    f"triton {triton.__version__}\n\n| shape | kernel | warps | time_us | "
                    f"current time_us | gain % | bytes_equal | verdict |\n|---|---|---|---|---|---|---|---|\n")
            for r in rows:
                if "error" in r:
                    f.write(f"| {r['shape']} | {r['kernel']} | {r['warps']} | error: {r['error'][:80]} | | | | |\n")
                    continue
                v = "WIN" if r["gain_pct"] >= 5.0 and r["bytes_equal"] else "no clear win"
                f.write(f"| {r['shape']} | {r['kernel']} | {r['warps']} | {r['time_us']} | "
                        f"{r['ref_time_us']} | {r['gain_pct']} | {r['bytes_equal']} | {v} |\n")
        print("md:", a.md)


if __name__ == "__main__":
    main()
